# Generated by Django 4.2.15 on 2024-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('bestgrow', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
