# Generated by Django 4.2.15 on 2024-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_recommendedplants'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplants',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendedplants',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
