# Generated by Django 4.2.15 on 2024-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_recommendedplants_address_recommendedplants_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplants',
            name='water_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
